name: Docker Build & Push

on:
  push:
    branches:
      - main  # ✅ Triggers build when main is updated
  release:
    types: [published]  # ✅ Triggers when a new release is published

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: docker-build  # 🔒 Ensures secrets are only accessible in approved branches

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Determine Tag
        id: get_version
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            echo "IS_RELEASE=true" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
            echo "IS_RELEASE=false" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t deathmarcher/wos-countdown-bot:${{ env.TAG }} .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push deathmarcher/wos-countdown-bot:${{ env.TAG }}

      - name: Push 'latest' Tag for Releases
        if: env.IS_RELEASE == 'true'
        run: |
          docker tag deathmarcher/wos-countdown-bot:${{ env.TAG }} deathmarcher/wos-countdown-bot:latest
          docker push deathmarcher/wos-countdown-bot:latest
